### ISSUE TITLE
Type information is being lost between txns, causing Longs to overflow at Int.MaxValue

### ISSUE THREAD

**Issue by squid-lee** [nbronson/scala-stm#42]
Compare these two snippets.
In the first version the whole things runs with the same txn. The output is 'correct' i.e. the result is 
- (2147483645,2147483646)
- (2147483646,2147483647)
- (2147483647,2147483648)
- (2147483648,2147483649)
- (2147483649,2147483650)

```
import scala.concurrent.stm._

object Main extends App {
  val a = TArray[Long](List(Int.MaxValue - 2))
  atomic { implicit txn =>
  for (i <- 0 to 4) {
    val in = a(0)
    a.update(0, in + 1)
    val out = a(0)
    println(in, out)
    }
  }
}
```

In the second version, the Longs values overflow at some point. When the value is put in to the array it's correct, but when it's retrieved _in a different txn_ it's retreived as an Int.
- (2147483645,2147483646)
- (2147483646,2147483647)
- (2147483647,2147483648)
- (-2147483648,-2147483647)
- (-2147483647,-2147483646)

```
import scala.concurrent.stm._

object Main extends App {
  val a = TArray[Long](List(Int.MaxValue - 2))
  for (i <- 0 to 4) {
    atomic { implicit txn =>
      val in = a(0)
      a.update(0, in + 1)
      val out = a(0)
      println(in, out)
    }
  }
}
```

**Comment by nbronson** [comment]
Fixed in 0.8 release
