### ISSUE TITLE
Scala STM interfered by Thread.sleep

### ISSUE THREAD

**Issue by fansgit** [nbronson/scala-stm#47]
I did a simple test on `scala 2.11.7` and `scala-stm_2.11 0.7` below, only the first `Future` completed. Both futures completed after `Thread.sleep` commented out.  Why?

``` scala
import scala.concurrent._
import ExecutionContext.Implicits.global
import scala.concurrent.stm._

object MySTM extends App {
  def myAtomic() = atomic { implicit txn =>
    Thread.sleep(0)
  }   
  Future { myAtomic() } onComplete { case _ => println("f1 done") }
  Future { myAtomic() } onComplete { case _ => println("f2 done") }
}
```

**Comment by Sciss** [comment]
just a guess - I think the default exec context only creates daemon threads, which means the JVM exits if there is no more non-daemon thread (e.g. main thread) running. this could be the reason you are seeing inconsistent reporting back from the two futures, and probably has nothing to do direclty with the `Thread.sleep`.

**Comment by nbronson** [comment]
@Sciss is right, this is a thread race. Try adding a Thread.sleep(1) in the main thread after you spawn the futures, or wait for them to finish.
