### ISSUE TITLE
2.12 builds

### ISSUE THREAD

**Issue by jroper** [nbronson/scala-stm#48]
Any chance that 0.7.0 could be built/published against 2.12.0-M2?

**Comment by povder** [comment]
Hi @nbronson, Scala 2.12.0 final has been published, it would be cool to see a stm build built against it :)

**Comment by jopasserat** [comment]
As we rely on scala-stm in @openmole, we have some pre-built artefacts for Scala 2.11 and 2.12 on our own maven repo:
https://repository.iscpif.fr/maven/org/scala-stm/

This is built from @zenaptix-lab's [fork](https://github.com/zenaptix-lab/scala-stm).

Can't promise this will be a reliable solution for the years to come but hopefully it can help until an official release becomes available.

_Thanks @romainreuillon for the build._

**Comment by liff** [comment]
Looks like [0.8 has been published](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scala-stm_2.12%22)?

**Comment by nbronson** [comment]
Yes. I'll update the web site today to match.
