### ISSUE TITLE
Txn.afterCompletion runs in separate thread?

### ISSUE THREAD

**Issue by elfprince13** [nbronson/scala-stm#51]
I'm working on some code that deals with an interface between locking datastructures and STM code. I have an `afterCompletion` hook that handles unlocking as necessary, but I've noticed that `Thread.currentThread.getId` returns a different value when executing that hook than it did during the transaction proper (when the lock was acquired). Since I have control over the locking implementation, I was able to implement a promiscuous variant that doesn't complain (i.e. throw exceptions) when this happens, but I'm concerned that it really shouldn't be happening at all.

**Comment by Sciss** [comment]
I have never heard about this. This works for me as expected:

```scala
import scala.concurrent.stm._

val x = Ref(1)
var txnThread: Thread = _

atomic { implicit tx =>
  x += 1
  txnThread = Thread.currentThread()
  Txn.afterCommit { _ =>
    val thisThread = Thread.currentThread()
    val status = if (thisThread == txnThread) "Ok" else "Different!"
    println(status)
  }
}
```

**Comment by elfprince13** [comment]
Hmm, seems to be have been a reentrancy related bug in my implementation. Sorry for the false alarm.
