### ISSUE TITLE
Release for Scala 2.13.0-M4

### ISSUE THREAD

**Issue by marcospereira** [nbronson/scala-stm#68]
This may require some additional code changes due to the changes in the Scala collections API.

**Comment by MasseGuillaume** [comment]
I'm on it.

**Comment by MasseGuillaume** [comment]
https://github.com/scala-stm/scala-stm/pull/4

**Comment by SethTisue** [comment]
2.13 support is now in place over at https://github.com/scala-stm/scala-stm (thx @xuwei-k for the heads-up)
